"""User.is_staff field

Revision ID: 52acdb16b175
Revises: 59f1f52ca42a
Create Date: 2025-11-29 16:13:10.327163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52acdb16b175"
down_revision: Union[str, Sequence[str], None] = "59f1f52ca42a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_staff", sa.Boolean(), nullable=True, default=False)
    )
    op.execute("UPDATE users SET is_staff = False")
    op.alter_column("users", "is_staff", nullable=False)

    op.drop_index("ix_products_seller_id", "products")
    op.drop_constraint("products_seller_id_fkey", "products", type_="foreignkey")
    op.drop_column("products", "seller_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_staff")
    op.add_column("products", sa.Column("seller_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "products_seller_id_fkey", "products", "users", ["seller_id"], ["id"]
    )
    op.create_index("ix_products_seller_id", "products", ["seller_id"], unique=False)
    # ### end Alembic commands ###
